version: '3.7'

services: 
  main:
    container_name: main
    restart: unless-stopped
    build:
      context: .
      target: development
    volumes: 
      - .:/usr/src/app
      - /usr/src/node_modules
    ports: 
      - ${SERVER_PORT}:3000
      - 9229:9229
    command: npm run start:dev
    env_file: 
      - .env
    networks: 
      - webnet
      - elastic
    links:
      - mysql
      - redis
    depends_on: 
      - redis
      - mysql
  redis:
    container_name: redis
    image: redis:6.0-alpine
    restart: unless-stopped
    networks: 
      - webnet
    ports:
      - 6379:6379
    volumes: 
      - redis_data:/data
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    networks: 
      - webnet
    restart: unless-stopped
    environment: 
      - REDIS_HOSTS=local:redis:6379
    ports: 
      - "8081:8081"
    depends_on: 
      - redis
  mysql:
    platform: linux/x86_64
    container_name: mysql
    image: mysql:5.7
    networks: 
      - webnet
    restart: unless-stopped
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports: 
      - 3306:${MYSQL_PORT}
    volumes: 
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql:${MYSQL_HOST}
    depends_on:
      - mysql
    ports:
      - 8080:80
    networks: 
      - webnet
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PMA_ARBITRARY: 0
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: ${MYSQL_PORT}

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic

volumes:
  mysql_data:
  redis_data:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local
networks: 
  webnet:
    driver: bridge
  elastic:
    driver: bridge